jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-latest
    strategy:
      maxParallel: 3
      matrix:
        node-15:
          node_version: ^15.0.0
        node-14:
          node_version: ^14.15.0
        node-12:
          node_version: ^12.4.0
        node-10:
          node_version: ^10.10.0
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: "Install Node.js $(node_version)"
      - script: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
        displayName: "Install Yarn"
      - script: |
          set -e
          export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
          node -v
          yarn -v
        displayName: "Print versions"
      - script: |
          set -e
          export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
          yarn
        displayName: "Install dependencies"
      - script: |
          set -e
          export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
          yarn cover --report lcovonly
        env:
          WATCHPACK_POLLING: 200
        displayName: "Run tests with coverage"

  - job: Windows
    pool:
      vmImage: windows-latest
    strategy:
      maxParallel: 3
      matrix:
        node-15:
          node_version: ^15.0.0
        node-14:
          node_version: ^14.15.0
        node-12:
          node_version: ^12.4.0
        node-10:
          node_version: ^10.10.0
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: "Install Node.js $(node_version)"
      - script: |
          npm install --global yarn
        displayName: "Install Yarn"
      - script: |
          set -e
          node -v
          yarn -v
        displayName: "Print versions"
      - script: |
          set -e
          yarn
        displayName: "Install dependencies"
      - script: |
          set -e
          yarn cover --report lcovonly
        env:
          WATCHPACK_POLLING: 200
        displayName: "Run tests with coverage"
